/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sistemas;

public class App {
    
   Define los combos y sus precios
combos = {
    1: {"nombre": "Hamburguesa y Perro caliente", "precio": 40000},
    2: {"nombre": "Crispetas con dos Gaseosas", "precio": 30000},
    3: {"nombre": "Dos Perros calientes con Dos Gaseosas", "precio": 42000}
}

Define los tipos de boletas y sus precios
boletas = {
    "G": {"nombre": "General", "precio": 10000},
    "V": {"nombre": "VIP", "precio": 15000}
}

Define los descuentos para los combos con boletas VIP
descuentos_vip = {
    1: 0.05,
    2: 0.06,
    3: 0.03
}

def calcular_factura():
    Solicita el tipo de boleta y la cantidad
    tipoboleta = input("Ingrese el tipo de boleta (G o V): ")
    cantidad_boletas = int(input("Ingrese la cantidad de boletas: "))

    Solicita el combo y la cantidad
    numerocombo = int(input("Ingrese el número del combo (1, 2 o 3): "))
    cantidadcombos = int(input("Ingrese la cantidad de combos: "))

    Calcula el valor total de las boletas
    valorboletas = boletas[tipoboleta]["precio"] * cantidadboletas

    Calcula el valor neto del combo
    valorcombo = combos[numerocombo]["precio"] * cantidadcombos

    Aplica el descuento si la boleta es VIP
    if tipoboleta == "V":
        descuento = valorcombo * descuentosvip[numerocombo]
    else:
        descuento = 0

    Calcula el valor total de la factura
    valortotal = valorboletas + valorcombo - descuento

    Muestra la factura
    print("\n**Factura**")
    print(f"Tipo de silla: {boletas[tipo_boleta]['nombre']} - Cantidad: {cantidadboletas}")
    print(f"Valor total de las boletas: ${valor_boletas:,.0f}")
    print(f"Combo: {combos[numerocombo]['nombre']} - Cantidad: {cantidadcombos}")
    print(f"Valor neto del combo: ${valorcombo:,.0f}")
    print(f"Descuento: ${descuento:,.0f}")
    print(f"Valor total: ${valor_total:,.0f}")

calcularfactura()

    public static void main(String[] args) {
        
    }
}
